title: onlinegoal.nl
author: Onlinegoal.nl
email: martijn@onlinegoal.nl
description: > # this means to ignore newlines until "baseurl:"
  Onlinegoal.nl website based on Starter Materialize Templates for Jekyll

sass:
    style: compressed

include: ['_pages']
