title: onlinegoal.nl
author: Onlinegoal.nl
email: martijn@onlinegoal.nl
description: > # this means to ignore newlines until "baseurl:"
  Online doeltreffendheid bereik je door dat te doen wat je klant wilt: engagement door het maken van content waarbij de gebruiker centraal staat.

baseUrl: onlinegoal.nl
exclude: ['CODE_OF_CONDUCT.md', '.idea']
include: ['_pages']

sass:
    style: compressed

plugins:
  - jekyll-sitemap
