title: onlinegoal.nl
author: Onlinegoal.nl
email: martijn@onlinegoal.nl
description: > # this means to ignore newlines until "baseurl:"
  Online doeltreffendheid bereik je door dat te doen wat je klant wilt: engagement door het maken van content waarbij de gebruiker centraal staat.sss

baseUrl: www.onlinegoal.nl
lang: nl_NL
twitter:
  card: summary
logo: /assets/website-laten-maken-logo.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      image: /assets/website-laten-maken-logo.png


exclude: ['CODE_OF_CONDUCT.md', '.idea']
include: ['_pages']

sass:
    style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
